trigger:
  - master

pr:
  - master

variables:
  imageName: 'jasonhindulak/go-rest-api-example'

resources:
  containers:
    - container: postgres
      image: postgres:12
      ports:
        - 5432:5432
      env:
        POSTGRES_PASSWORD: thispasswordissecret
        POSTGRES_DB: contacts

jobs:
  - job: CI
    services:
      postgres: postgres
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - script: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          ~/go/bin/golangci-lint run ./...
        displayName: Go Lint
      - task: HelmInstaller@1
        displayName: Helm installer
        inputs:
          helmVersionToInstall: 2.14.3
      - script: helm lint $(System.DefaultWorkingDirectory)/deployments/helm/go-rest-api/ --strict
        displayName: Helm Lint
      - script: |
          go test ./... -v -cover
        displayName: Unit Tests
        continueOnError: true
      - script: |
          mkdir dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/go-rest-api -v main.go
        displayName: Build
      - script: |
          go get -u github.com/jstemmer/go-junit-report
          export token_password="secretpassword" MASTER_USERNAME="postgres" MASTER_PASSWORD="thispasswordissecret" \
            DB_NAME="contacts" ENDPOINT_ADDRESS="localhost" DB_PORT="5432"
          go test -tags=integration ./... -v -cover 2>&1 | ~/go/bin/go-junit-report -set-exit-code > report.xml
      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
        condition: always()
        displayName: Integration Tests
      - script: docker build -t $(imageName):$(build.buildId) -t $(imageName):latest .
        displayName: Docker Build
      - task: HelmDeploy@0
        inputs:
          command: 'package'
          chartPath: '$(System.DefaultWorkingDirectory)/deployments/helm/go-rest-api'
          chartVersion: '1.0.0'
        displayName: Package Helm Chart
      - script: |
          docker login -u $(dockerId) -p $(dockerPassword)
          docker push $(imageName):$(build.buildId)
          docker push $(imageName):latest
        displayName: Docker Push
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'helm-chart'
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        displayName: Publish Helm Chart as Artifact
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
