trigger:
  - master

pr:
  - master

variables:
  imageName: 'jasonhindulak/go-rest-api-example'

jobs:
<<<<<<< HEAD
  - job: CI
=======
  - job: Tests
>>>>>>> master
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - script: |
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          ~/go/bin/golangci-lint run ./...
<<<<<<< HEAD
        displayName: Lint
      - script: go test -cover ./...
        displayName: Unit Tests
      - script: |
          mkdir dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/go-rest-api -v main.go
        displayName: Build
      - script: docker build -t $(imageName):$(build.buildId) -t $(imageName):latest .
        displayName: Docker Build
=======
        displayName: 'lint'
      - script: go test -cover ./...
        displayName: 'unit tests'
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - script: |
          mkdir dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/go-rest-api -v main.go
        displayName: 'build'
      - script: docker build -t $(imageName):$(build.buildId) -t $(imageName):latest .
        displayName: 'docker build'
  - job: Push_Artifacts
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Tests
      - Build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
>>>>>>> master
      - script: |
          docker login -u $(dockerId) -p $(dockerPassword)
          docker push $(imageName):$(build.buildId)
          docker push $(imageName):latest
<<<<<<< HEAD
        displayName: Docker Push
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
=======
        displayName: 'docker push'
>>>>>>> master
