trigger:
  - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'jasonhindulak/go-rest-api-example:$(build.buildId)'

steps:
  - script: |
      mkdir dist
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/go-rest-api -v main.go
    displayName: 'build'
  - script: go test -cover ./...
    displayName: 'test'
  - script: docker build -t $(imageName) .
    displayName: 'docker build'
  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(imageName)
    displayName: 'docker push'