version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.local
      context: .
    ports:
      - "8080:80"
    environment:
      token_password: secretpassword
      MASTER_USERNAME: postgres
      MASTER_PASSWORD: thispasswordissecret
      DB_NAME: contacts
      ENDPOINT_ADDRESS: db
      DB_PORT: 5432
      listen_port: 80
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: thispasswordissecret
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"