FROM golang:1.12 as builder

COPY . /app
WORKDIR /app

RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint && \
    golangci-lint run ./... && \
    mkdir /dist && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /dist/go-rest-api -v main.go

FROM scratch

WORKDIR /app
COPY --from=builder /dist/go-rest-api /app

CMD ["/app/go-rest-api"]