apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-rest-api.fullname" . }}
data:
  listen_port: {{ default 80 .Values.config.listen_port | quote }}
  token_password: {{ required "A valid .Values.config.token_password entry is required" .Values.config.token_password }}
  MASTER_USERNAME: {{ .Values.config.MASTER_USERNAME | quote }}
  MASTER_PASSWORD: {{ .Values.config.MASTER_PASSWORD | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  ENDPOINT_ADDRESS: {{ .Values.config.ENDPOINT_ADDRESS | quote }}